server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/word_check?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 199509
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    repair-on-migrate: true
    
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wordcheck.model
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-statement-timeout: 30
    
# JWT配置
jwt:
  secret: your_jwt_secret_key_must_be_at_least_32_characters_long
  expiration: 604800 # 7天，单位秒

# 微信小程序配置
weixin:
  appid: wxa80c1fbffae22654
  secret: 638c106f2a59ab06c7c3660d86da2bed