server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/word_check?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 199509
    
  flyway:
    enabled: true
    
logging:
  level:
    com.wordcheck: debug
    org.springframework: info
    org.mybatis: debug 